snowsql_config_path = "/Users/jhansen/.snowsql/config"
snowsql_connection_name = "dev"

[default]
input_parameters = "(temp_f float)"
return_type = "float"
file = "app.zip"
name = "fahrenheit_to_celsius_udf"
handler = "app.main"

[dev]
database = "HOL_DB"
schema = "HARMONIZED"
warehouse = "HOL_WH"
role = "HOL_ROLE"
overwrite = true
