snowsql_config_path = "~/.snowsql/config"
snowsql_connection_name = "se_dedemo"

[default]
input_parameters = "()"
return_type = "string"
file = "app.zip"
name = "orders_update_sp"
handler = "app.main"
execute_as_caller = true

[dev]
database = "hol_db"
schema = "harmonized"
role = "hol_role"
warehouse = "hol_wh"
overwrite = true
